Vagrant.configure("2") do |config|
  
  boxes = [
    {
      :name => "docker-jenkins-ansible",
      :box => "geerlingguy/debian9"
    }
  ] 

  boxes.each do |opts|

    config.vm.provider "virtualbox" do |vb|
      # vb.memory = 8192
      # vb.cpus = 2
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end

    config.vm.define opts[:name] do |config|
      
      config.vm.box = opts[:box]

      config.vm.synced_folder "../", "/docker-jenkins-ansible"

      config.vm.network "private_network", type: "dhcp"

      if opts[:name] == boxes.last[:name]
        config.vm.provision "ansible" do |ansible|
          
          ansible.playbook = "main.yml"

          ansible.limit = "all"
        end
      end
    end
  end
end
  